### ISSUE TITLE
Produced a corrupt pdf, fixed it

### ISSUE THREAD

**Issue by languagemaniac** [Leseratte10/acsm-calibre-plugin#101]
### Bug description

Hi, I use this plugin frequently and never had any issues with it. But today I converted a acsm file to pdf and it produced a partially corrupt pdf. Acrobat reader and some other pdf readers could only see the bookmarks, the cover page, and the number of pages. But trying to see other pages resulted in error saying "There was a problem processing a page . There was a problem reading this document (110)"

Some time ago I had an issue with a pdf I downloaded from somewhere else. A page wouldn't load and fixed it by opening and saving it with a program called nitro pdf.

So I decided to do the same for this one, and to my surprise, it could read the entire thing fine, so I saved it and that's how I fixed it. The saved file doesn't produce any errors in acrobat reader or some other pdf readers I tested the damaged pdf with.

How could I help? Can I provide any logs (if so, how?) or can I send you the acsm file?

### Operating system

Windows

### Which version of Calibre are you running?

7.16.0

### Which version of the ACSM Input plugin are you running?

v0.0.16

### Import type

Dragging-and-Dropping the ACSM file into the Calibre window

### Further information

Tried opening with ABBY finereader, photoshop, adobe illustrator. Those can't read it,

Just tried opening with google chrome and it can read it fine, so not sure what the issue is

**Comment by Leseratte10** [comment]
You can try to test if the latest beta version from the Github actions fixes the problem, I've fixed a couple PDF issues there. 

If that doesn't help, I would need to have the link to the encrypted PDF file. It will show up in the verbose log that can be created by enabling the verbose log setting, then right-clicking the "Preferences" button in Calibre and choose "Restart in debug mode". Then import the ACSM and close Calibre.

**Comment by languagemaniac** [comment]
> You can try to test if the latest beta version from the Github actions fixes the problem, I've fixed a couple PDF issues there.

I am using the latest version 0.0.16, is there another more advanced version? Can't find it.

Can you provide me with an email address to send you the acsm file privately

**Comment by Leseratte10** [comment]
That's the latest release, there's a newer beta here: https://github.com/Leseratte10/acsm-calibre-plugin/actions/runs/10280358906/artifacts/1784495838 

You can send an email to "s4-tmp-ar4jg5on92nd-github-acsm-101@leseratte10.de". Note that the ACSM is probably not that useful for me since it's now already linked to your Adobe account. What I would need is the verbose debug log of you importing that ACSM into Calibre with your account.

**Comment by languagemaniac** [comment]
> That's the latest release, there's a newer beta here: https://github.com/Leseratte10/acsm-calibre-plugin/actions/runs/10280358906/artifacts/1784495838
> 
> You can send an email to "[s4-tmp-ar4jg5on92nd-github-acsm-101@leseratte10.de](mailto:s4-tmp-ar4jg5on92nd-github-acsm-101@leseratte10.de)". Note that the ACSM is probably not that useful for me since it's now already linked to your Adobe account. What I would need is the verbose debug log of you importing that ACSM into Calibre with your account.

Ok I misunderstood. I sent you the verbose log of the import

**Comment by spreepatient** [comment]
> That's the latest release, there's a newer beta here: https://github.com/Leseratte10/acsm-calibre-plugin/actions/runs/10280358906/artifacts/1784495838
> 
> You can send an email to "[s4-tmp-ar4jg5on92nd-github-acsm-101@leseratte10.de](mailto:s4-tmp-ar4jg5on92nd-github-acsm-101@leseratte10.de)". Note that the ACSM is probably not that useful for me since it's now already linked to your Adobe account. What I would need is the verbose debug log of you importing that ACSM into Calibre with your account.

I have the same problem as @languagemaniac and have tried your current bulid. Unfortunately, the error still occurs. I have activated verbose logging and repeated the import. Where can I find the logging?

**Comment by Leseratte10** [comment]
In Calibre, right-click the "Preferences" button then choose "Restart in debug mode". Then import the file again and close Calibre, and a window with the logfile will pop up.

**Comment by spreepatient** [comment]
You have received an e-mail with the log to the address you provided here in the thread.

**Comment by Leseratte10** [comment]
Thanks. I took a look at that log and it looks like my plugin did everything right creating the PDF file and the issue is with DRM removal. Try updating the DeDRM plugin and if that doesn't help, you'll probably have to open an issue on the DeDRM github.

**Comment by spreepatient** [comment]
> Thanks. I took a look at that log and it looks like my plugin did everything right creating the PDF file and the issue is with DRM removal. Try updating the DeDRM plugin and if that doesn't help, you'll probably have to open an issue on the DeDRM github.

Thank you. You were absolutely right. I downloaded the latest beta 10.0.9 of noDRM and it worked.
